### PR TITLE
Fix SDKHooks weapon drop bug for SM 1.9

### LINKED ISSUE #5: SDKHooks weapon drop bugs out for SM 1.9
On SM 1.9, SDKHooks_DropWeapon call with the default NULL_VECTOR drop velocity throws an error:

> [SM] Exception reported: Could not read vecVelocity vector

Should return a zeroed out vec3 for the 1.9 branch.

### PR DESCRIPTION
**Pull request by Rainyan**
Fixes #5

### CODE REVIEW

**Comment by OlofMillberg-SATO** [comment]
Fun fact: There's currently a bug in SDKHooks where if you pass NULL_VECTOR the new bypassHooks argument will be ignored.

**Comment by Agiel** [comment]
Fun fact: There's currently a bug in SDKHooks where if you pass NULL_VECTOR the new bypassHooks argument will be ignored. So this is also good for future proofing 😅

**Comment by Rainyan** [comment]
Submitted a patch to SourceMod for it, fingers crossed it gets accepted. Although it still unfortunately leaves any backwards compatible plugins juggling with weird per-version hacks until they deprecate.

**Comment by Rainyan** [comment]
The bypassHooks bug should be now be fixed in the latest SM 1.12 dev snapshot (build 6961 or later)!

**Pull request merged**
